### ISSUE TITLE
Expire forced when token has no expires_in property

### ISSUE THREAD

**Issue by Trolleymusic** [andreareginato/oauth-ng#70] opened 2015-03-10 15:05 UTC
At the moment, when a server returns a token that has no `expires_in` property, the token is assumed to have expired.

The best solution (in my current case at least, and regardless of any code changes to oauth-ng), would be to change the server's response so that it includes `expires_in`, but when looking at the spec (http://tools.ietf.org/html/rfc6749#section-4.2.2), `expires_in` is marked as *recommended* only and not required.

I'd be happy to make any changes and open a pull request, but I thought you might have an opinion on how tokens that are missing this property should be dealt with?

**Comment by Trolleymusic** [comment] 2015-03-10 15:16
Hello again,

Ok, so the response from those who are in control of the server I'm authenticating against is that they don't send out the `expires_in` property because as far as they're concerned the token never expires.

If you're of the same opinion: that missing `expires_in` means that the token does not expire, then I'll change the directive & make a pull request, if not I'll do some hack-thing in my app and you can close this issue.

**Comment by elwin1234** [comment] 2015-05-09 14:03
Another issue about the 'setExpiresAtEvent': the maximum timeout for javascripts setInterval function (function that angular's $interval wraps) is:  4294967295 (32 bit int). This means  4294967295ms =  1193 hours = 49.71 days as max timeout. Some api's provide tokens that are valid for 3 months or longer. Because this time exceeds the maximum value the 'oauth:expired' is fired immediately.

**Comment by Trolleymusic** [comment] 2015-05-09 14:45
I've [opened a pull request](https://github.com/andreareginato/oauth-ng/pull/77) with my previously mentioned "hack-thing", which was a modification of the directive. Now that my other pull request is merged in, this is only a few extra lines of code.

@elwin1234, this doesn't resolve the problem you mentioned - but I'm not quite sure what will!

**Comment by elwin1234** [comment] 2015-05-21 11:41
@Trolleymusic thanks. I started a new issue, since the issue is not directly related to yours.

**Comment by m00s** [comment] 2015-05-26 22:40
close this from commit 0ff36e9a812127f9ac22c7baa9b1ebe632754183

**Closed by m00s** 2015-05-26 22:40 UTC
